
# Only for building cross compilation tools, 'os_target/arch_target' is the system for
# which the tools generate code
os_target:         [Windows, Linux, Macos, Android, iOS, watchOS, tvOS, FreeBSD, SunOS, AIX, Arduino, Neutrino, Wasi]
os_build:         [Windows, Linux, Macos, Android, iOS, watchOS, tvOS, FreeBSD, SunOS, AIX, Arduino, Neutrino, Wasi]
arch_target:       [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le]
arch_build:       [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le]

release: ANY
deployment:        [True, False]
gstreamer:         ["1.16", "1.18", "1.19", "1.20", "1.21", "1.22"]
python:            ["3.8", "3.9"]
rust:              ["1.48", "1.49", "1.50", "1.51", "1.52", "1.53", "1.54", "1.55", "1.56",
                    "1.57", "1.58", "1.59", "1.60", "1.61", "1.62", "1.63", "1.66"]
hardware:
  l4t:
    # NVIDIA Tegra devices - Linux for Tegra
      version:     ["32.2.1", "32.4.3"]
      # Xavier and TX2: t186
      # TX1 and Nano: t210
      board:       ["t186", "t210"]
  rpi:
    # Raspberry devices
      # Raspbian os version, if installed 
      version:     ["10", "20"]
      # RPi4: pi4
      board:       ["pi4"]
  odroid:
    # Odroid devices
      # os flashed on odroid
      version:     ["ubuntu", "android"]
      # Odroid: n2
      board:       ["n2"]
  generic:
dedicated_gpu:     [None, nvidia, amd]

build_type:        [None, Debug, Release, RelWithDebInfo, MinSizeRel]

libc:              [glibc, musl, bionic, wasi]
arch:              [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv4, armv4i, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le]
arch_build:              [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv4, armv4i, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le]
os:
    Windows:
        subsystem: [None, cygwin, msys, msys2, wsl]
    WindowsStore:
        version:   ["8.1", "10.0"]
    WindowsCE:
        platform:  ANY
        version:   ["5.0", "6.0", "7.0", "8.0"]
    Linux:
    Macos:
        version:   [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14", "10.15"]
    Android:
        api_level: ANY
    iOS:
        version:   ["7.0", "7.1", "8.0", "8.1", "8.2", "8.3", "9.0", "9.1", "9.2", "9.3", "10.0", "10.1", "10.2", "10.3", "11.0", "11.1", "11.2", "11.3", "11.4", "12.0", "12.1", "12.2", "12.3", "12.4", "13.0", "13.1"]
    watchOS:
        version:   ["4.0", "4.1", "4.2", "4.3", "5.0", "5.1", "5.2", "5.3", "6.0", "6.1"]
    tvOS:
        version:   ["11.0", "11.1", "11.2", "11.3", "11.4", "12.0", "12.1", "12.2", "12.3", "12.4", "13.0"]
    FreeBSD:
    SunOS:
    AIX:
    Arduino:
        board:     ANY
    Emscripten:
    Wasi:
    Neutrino:
        version:   ["6.4", "6.5", "6.6", "7.0"]
compiler:
    sun-cc:
        version:   ["5.10", "5.11", "5.12", "5.13", "5.14"]
        threads:   [None, posix]
        libcxx:    [libCstd, libstdcxx, libstlport, libstdc++]
    gcc:
        version:   ["4.1", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9",
                  "5", "5.1", "5.2", "5.3", "5.4", "5.5",
                  "6", "6.1", "6.2", "6.3", "6.4",
                  "7", "7.1", "7.2", "7.3", "7.4",
                  "8", "8.1", "8.2", "8.3",
                  "9", "9.1", "9.2"]
        libcxx:    [libstdc++, libstdc++11]
        threads:   [None, posix, win32] #  Windows MinGW
        exception: [None, dwarf2, sjlj, seh] # Windows MinGW
        cppstd:    [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]
    Visual Studio:
        runtime:   [MD, MT, MTd, MDd]
        version:   ["8", "9", "10", "11", "12", "14", "15", "16"]
        toolset:   [None, v90, v100, v110, v110_xp, v120, v120_xp,
                  v140, v140_xp, v140_clang_c2, LLVM-vs2012, LLVM-vs2012_xp,
                  LLVM-vs2013, LLVM-vs2013_xp, LLVM-vs2014, LLVM-vs2014_xp,
                  LLVM-vs2017, LLVM-vs2017_xp, v141, v141_xp, v141_clang_c2, v142]
        cppstd:    [None, 14, 17, 20]
    clang:
        version:   ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0",
                  "5.0", "6.0", "7.0", "7.1",
                  "8", "9", "10", "11", "12", "13", "14", "15"]
        libcxx:    [libstdc++, libstdc++11, libc++, c++_shared, c++_static]
        cppstd:    [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]
    apple-clang:
        version:   ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0", "8.1", "9.0", "9.1", "10.0", "11.0"]
        libcxx:    [libstdc++, libc++]
        cppstd:    [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]
    qcc:
        version:   ["4.4", "5.4"]
        libcxx:    [cxx, gpp, cpp, cpp-ne, accp, acpp-ne, ecpp, ecpp-ne]
